### PR TITLE
Fix many, many bugs

### LINKED ISSUE #13: Eraser tool doesn't work if drawing was loaded from JSON
Hello! Eraser tool doesn't work on drawing view if it's `drawing` property was set.
`do {
            self.drawingView.drawing = try JSONDecoder().decode(Drawing.self, from: data)
        } catch let error {
            print(error)
        }`
Any suggestions?
Thank you!

### PR DESCRIPTION
**Pull request by stevelandeyasana**
Fixes #13, #21, #27, and more unreported bugs.

# Docs

Fixes Jazzy docs to have correct categories on classes added by contributors.

# Unit tests

- The unit test target compiles
- Each shape has a serialization test
- `Drawing` also has serialization tests for different failure modes

# Bugs

## Shapes

- Ngons encode and decode properly
- Text now saves its bounding rect, because there's no way to derive it without the tool instance

## Drawing serialization

- Replacing `DrawingView.drawing` is much more correct
  - `DrawingView.drawingOperationStack` is replaced with a fresh instance that references the new drawing instance instead of hanging on to the old one
  - The tool is deactivated and reactivated to pick up new information
- Add static `Drawing.debugSerialization` flag. When the flag is disabled, shapes with decoding errors are skipped. When enabled, the errors are raised.

## Other

- `PenLineSegment`'s members are now public
- `PenLineSegment` and `ShapeTransform` are equatable

### CODE REVIEW

File: Drawsana Demo/ViewController.swift [hunk 1]
```diff
@@ -51,13 +51,15 @@ class ViewController: UIViewController {
   let strokeColorButton = UIButton()
   let fillColorButton = UIButton()
   let strokeWidthButton = UIButton()
+  let reloadButton = UIButton()
```
Comment (stevelandeyasana) [inline Drawsana Demo/ViewController.swift]: This is a simple change to the demo app to make serialization testing easy.

File: Drawsana/DrawsanaView.swift [hunk 2]
```diff
@@ -8,7 +8,7 @@
 
 import UIKit
 
-public let DRAWSANA_VERSION = "1.0"
+public let DRAWSANA_VERSION = "0.9.5"
```
Comment (stevelandeyasana) [inline Drawsana/DrawsanaView.swift]: Oops.

File: Drawsana/Data model/Drawing.swift [hunk 3]
```diff
@@ -83,20 +95,25 @@ public class Drawing: Codable {
...
+        // move on.
+        if Drawing.debugSerialization {
+          throw DrawsanaDecodingError.unknownShapeTypeError(type)
+        }
       }
     }
   }
 
-  private func tryDecodingAllShapes(_ container: inout UnkeyedDecodingContainer) -> [Shape] {
+  private func tryDecodingAllShapes(_ container: inout UnkeyedDecodingContainer) throws -> [Shape] {
```
Comment (TheDom) [inline Drawsana/Data model/Drawing.swift]: [nit] We might want to remove `try` from this method name as well as `tryDecoding()` now that they throw errors. It looks weird that the calls are e.g. `try tryDecodingAllShapes(...)`.

File: Drawsana/Data model/Drawing.swift [hunk 4]
```diff
@@ -173,10 +191,13 @@ public class MultiDecoder<ResultType> {
 
   /// Adds the decoded result to `results` if decoding succeeds, otherwise does
   /// nothing.
-  public func tryDecoding<T: Shape>(_ type: T.Type) {
+  public func tryDecoding<T: Shape>(_ type: T.Type) throws {
```
Comment (TheDom) [inline Drawsana/Data model/Drawing.swift]: I would recommend to document which errors this method can throw. The comment ("...otherwise does nothing.") feels slightly confusing now.

File: Drawsana/Shapes/Implementations/PenShape.swift [hunk 5]
```diff
@@ -9,14 +9,18 @@
...
+  public var a: CGPoint
+  public var b: CGPoint
+  public var width: CGFloat
 
-  var midPoint: CGPoint {
+  public var midPoint: CGPoint {
     return CGPoint(x: (a.x + b.x) / 2, y: (a.y + b.y) / 2)
   }
+
+  public static func ==(_ a: PenLineSegment, _ b: PenLineSegment) -> Bool {
```
Comment (TheDom) [inline Drawsana/Shapes/Implementations/PenShape.swift]: Is this implementation necessary? Since Swift 4.1 `Equatable` conformance is automatically generated if possible. Refer to https://github.com/apple/swift-evolution/blob/master/proposals/0185-synthesize-equatable-hashable.md

File: Drawsana/Shapes/ShapeTransform.swift [hunk 6]
```diff
@@ -12,12 +12,18 @@ import CoreGraphics
...
  */
-public struct ShapeTransform: Codable {
+public struct ShapeTransform: Codable, Equatable {
   public var translation: CGPoint
   public var rotation: CGFloat
   public var scale: CGFloat
 
   public static let identity = ShapeTransform(translation: .zero, rotation: 0, scale: 1)
+
+  public static func ==(_ a: ShapeTransform, _ b: ShapeTransform) -> Bool {
```
Comment (TheDom) [inline Drawsana/Shapes/ShapeTransform.swift]: Same as above
